return {
    smile = string.char(2),
    heart = string.char(3),
    diamond = string.char(4),
    clubs = string.char(5),
    spades = string.char(6),
    dot = string.char(7),
    dotInverted = string.char(8),
    male = string.char(11),
    female = string.char(12),
    note1 = string.char(14),
    note2 = string.char(15),
    spikeRight = string.char(16),
    spikeLeft = string.char(17),
    arrowUpDown = string.char(18),
    doubleExclamation = string.char(19),
    paragraphSign = string.char(20),
    sectionSign = string.char(21),
    arrowUpDownUnderscore = string.char(23),
    sectionSign = string.char(21),
    arrowUp = string.char(24),
    arrowDown = string.char(25),
    arrowRight = string.char(26),
    arrowLeft = string.char(27),
    spikeUp = string.char(30),
    spikeDown = string.char(31),
}